#Archivo de Configuracion para SMSGUBIA

mensajePrueba: Hola buen dia este es un mensaje de prueba del servicio de mensajes de texto !n *http://www.goo.gl/ymh2Ab enviado el {} !n --Mensaje generado de manera automática favor de no contestar. !n --Si no puede acceder a sus resultados agregue este numero a sus contactos.
telefonosPrueba : ['5554374058', '7971109731', '2223178965']
horaPrueba: 8
esperaWhatsMenor: 20
esperaWhatsMayor: 45
esperaMantenimiento: 900  
erroresParaMantenimiento: 3
logger:
  archivo: /home/pi/gubiaSms/log.log
gubiaBoot:
  token: 883742257:AAHZTho53C3Z5W2fR4kh727c1agxC2voxBQ
  chatId: 326212885
  chatIdGrupo: -429562103
baseDatos:
  host: sql5007.site4now.net
  username: DB_9AE2E9_bdGubia_admin
  password: gubia123...
  database: DB_9AE2E9_bdGubia
  tablaEntrada: tbSmsSalidaTest
  whatsAppSalida: SmsWhatsapp 
  tablaNoEnviados: SmsMensajesNoEnviados
  tablaMantenimiento: SmsGubiaMantenimiento
  tablaErrores: SmsMensajesErrores 
  numeroRegistros: 5
  numeroReintentos: 5
peopleApi:
  token: token.json
  credentials: credentials.json
whatsApp:
  token: c5ff71bb46d0d7556c0f7da497fdbabf5d7295bfdcd50
  archivoContador: whats.cont
  diferenciador: prue-
  uid: "527971416893"

